.\" 
.\" missdeps manual page.
.\" (C) 2025 by Petar Petrov <slackalaxy@gmail.com> 
.\"
.TH missdeps 1
.SH NAME
missdeps \- Check for missing deps of all packages that are installed.
.SH SYNOPSIS
.PP
.B missdeps
.SH DESCRIPTION

The \fBmissdeps\fP script uses \fBprt\-get listinst\fP(8) to check for missing 
dependencies of the packages that are installed, then reports them and
outputs their immediate installed dependents. It will also notify you, if
there are there missing deps that have no ports.

.SH OPTIONS
.TP
no options available

.SH EXAMPLES
.PP
Display dependencies that are missing from the system as a list:

.B
missdeps
.PP
.nf
.fam C
eudev
sqlite3
.fam T
.fi

.PP
Display dependencies that are missing from the system, and the installed
package(s), dependent on them:

.B
missdeps -v

.PP
.nf
.fam C
-- ([ ] missing deps, [d] = dependents)
[ ] eudev
[ ] sqlite3
[d] apr-util
[d] dhcpcd
[d] libinput
[d] libusb
[d] nss
[d] openmpi
[d] pciutils
[d] python3
[d] util-linux
.fam T
.fi

.SH SEE ALSO
\fBprt\-get\fP(8), \fBports\fP(8), \fBrevdep\fP(1)

.SH AUTHOR

\fBmissdeps\fP was written by Petar Petrov <slackalaxy@gmail.com> for CRUX.
